import type { Task } from "../types/task"

// Sample data for the application
const sampleData: Task[] = [
  {
    id: "1",
    title: "UX/UI Design in the Age of AI",
    description: "Research and implement AI-driven UX/UI design principles",
    status: "todo",
    priority: "high",
    progress: 52,
    project: "Design System",
    assignees: ["John Doe", "Jane Smith"],
    comments: 987,
    completedItems: 2100,
    createdAt: "2023-03-01T12:00:00Z",
    updatedAt: "2023-03-10T15:30:00Z",
    dueDate: "2023-04-15T23:59:59Z",
    tags: ["design", "research", "ai"],
  },
  {
    id: "2",
    title: "Responsive Website Design for 23 more clients",
    description: "Create responsive designs for multiple client websites",
    status: "todo",
    priority: "low",
    progress: 0,
    project: "Client Projects",
    assignees: ["John Doe"],
    comments: 115,
    completedItems: 0,
    createdAt: "2023-03-05T09:00:00Z",
    updatedAt: "2023-03-05T09:00:00Z",
    dueDate: "2023-04-20T23:59:59Z",
    tags: ["design", "responsive"],
  },
  {
    id: "3",
    title: "Blog Copywriting (Low priority)",
    description: "Write blog posts for the company website",
    status: "todo",
    priority: "medium",
    progress: 0,
    project: "Content Marketing",
    assignees: ["Jane Smith"],
    comments: 67,
    completedItems: 1,
    createdAt: "2023-03-07T14:00:00Z",
    updatedAt: "2023-03-07T14:00:00Z",
    dueDate: "2023-04-25T23:59:59Z",
    tags: ["content", "writing"],
  },
  {
    id: "4",
    title: "Machine Learning Progress",
    description: "Implement machine learning algorithms for data analysis",
    status: "in-progress",
    priority: "high",
    progress: 52,
    project: "Data Science",
    assignees: ["Alex Johnson"],
    comments: 13,
    completedItems: 52,
    createdAt: "2023-02-20T10:00:00Z",
    updatedAt: "2023-03-08T16:45:00Z",
    dueDate: "2023-04-10T23:59:59Z",
    tags: ["machine-learning", "ai", "data"],
  },
  {
    id: "5",
    title: "Learn Computer Science",
    description: "Study computer science fundamentals",
    status: "in-progress",
    priority: "medium",
    progress: 28,
    project: "Education",
    assignees: ["Sarah Lee"],
    comments: 99,
    completedItems: 13,
    createdAt: "2023-02-15T08:30:00Z",
    updatedAt: "2023-03-09T11:20:00Z",
    dueDate: "2023-05-01T23:59:59Z",
    tags: ["education", "computer-science"],
  },
  {
    id: "6",
    title: "User flow confirmation for fintech App",
    description: "Finalize user flows for the fintech application",
    status: "completed",
    priority: "high",
    progress: 100,
    project: "Fintech App",
    assignees: ["John Doe", "Alex Johnson"],
    comments: 201,
    completedItems: 1800,
    createdAt: "2023-02-01T09:15:00Z",
    updatedAt: "2023-03-01T14:30:00Z",
    completedAt: "2023-03-01T14:30:00Z",
    dueDate: "2023-03-01T23:59:59Z",
    tags: ["fintech", "ux", "design"],
  },
  {
    id: "7",
    title: "API Integration for Payment Gateway",
    description: "Integrate payment gateway APIs into the platform",
    status: "todo",
    priority: "high",
    progress: 15,
    project: "Payment System",
    assignees: ["Alex Johnson", "Sarah Lee"],
    comments: 45,
    completedItems: 8,
    createdAt: "2023-03-10T11:00:00Z",
    updatedAt: "2023-03-12T16:20:00Z",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(), // Due tomorrow
    tags: ["api", "payment", "integration"],
  },
  {
    id: "8",
    title: "Mobile App UI Redesign",
    description: "Redesign the mobile app user interface",
    status: "todo",
    priority: "medium",
    progress: 30,
    project: "Mobile App",
    assignees: ["Jane Smith"],
    comments: 78,
    completedItems: 25,
    createdAt: "2023-03-08T13:45:00Z",
    updatedAt: "2023-03-11T10:15:00Z",
    dueDate: new Date().toISOString(), // Due today
    tags: ["design", "mobile", "ui"],
  },
  {
    id: "9",
    title: "Database Optimization",
    description: "Optimize database queries for better performance",
    status: "in-progress",
    priority: "high",
    progress: 65,
    project: "Backend Infrastructure",
    assignees: ["Alex Johnson"],
    comments: 32,
    completedItems: 40,
    createdAt: "2023-03-05T09:30:00Z",
    updatedAt: "2023-03-10T14:20:00Z",
    dueDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(), // Overdue
    tags: ["database", "optimization", "performance"],
  },
  {
    id: "10",
    title: "Documentation Update",
    description: "Update API documentation with new endpoints",
    status: "completed",
    priority: "low",
    progress: 100,
    project: "Documentation",
    assignees: ["Sarah Lee"],
    comments: 15,
    completedItems: 30,
    createdAt: "2023-03-01T10:00:00Z",
    updatedAt: "2023-03-05T16:30:00Z",
    completedAt: "2023-03-05T16:30:00Z",
    dueDate: "2023-03-07T23:59:59Z",
    tags: ["documentation", "api"],
  },
  {
    id: "11",
    title: "User Testing Session",
    description: "Conduct user testing for the new features",
    status: "completed",
    priority: "medium",
    progress: 100,
    project: "User Research",
    assignees: ["Jane Smith", "Sarah Lee"],
    comments: 56,
    completedItems: 42,
    createdAt: "2023-02-25T11:15:00Z",
    updatedAt: "2023-03-08T15:45:00Z",
    completedAt: "2023-03-08T15:45:00Z",
    dueDate: "2023-03-10T23:59:59Z",
    tags: ["testing", "research", "ux"],
  },
  {
    id: "12",
    title: "Security Audit",
    description: "Perform security audit on the application",
    status: "completed",
    priority: "high",
    progress: 100,
    project: "Security",
    assignees: ["Alex Johnson"],
    comments: 89,
    completedItems: 75,
    createdAt: "2023-02-20T09:00:00Z",
    updatedAt: "2023-03-02T17:30:00Z",
    completedAt: "2023-03-02T17:30:00Z",
    dueDate: "2023-03-05T23:59:59Z",
    tags: ["security", "audit"],
  },
  {
    id: "13",
    title: "Marketing Campaign Planning",
    description: "Plan the Q2 marketing campaign",
    status: "todo",
    priority: "medium",
    progress: 20,
    project: "Marketing",
    assignees: ["Jane Smith", "Sarah Lee"],
    comments: 67,
    completedItems: 12,
    createdAt: "2023-03-12T13:00:00Z",
    updatedAt: "2023-03-14T11:45:00Z",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(), // Due in 5 days
    tags: ["marketing", "planning"],
  },
]

// Function to fetch data from either local JSON or API
export async function fetchData(useApi = false): Promise<Task[]> {
  if (useApi) {
    try {
      // This is a simulated API call
      // In a real application, you would replace this with an actual API endpoint
      return new Promise((resolve) => {
        setTimeout(() => {
          resolve(sampleData)
        }, 800) // Simulate network delay
      })
    } catch (error) {
      console.error("Error fetching data from API:", error)
      return sampleData // Fallback to local data
    }
  } else {
    // Return local data
    return sampleData
  }
}

